Fix warning when closing / deleting unsaved document
New (un-autosaved) documents don't yet have a _store, so attempting to
remove the persistent store coordinator upon document close results in
an error, which gets NSLogged. Return success from
removePersistentStoreWithError: when _store is nil, because there is
nothing to remove.